"""Schemathesis API schema tests for FastAPI web server.

This module uses Schemathesis to test the web server endpoints against
the OpenAPI schema generated by FastAPI. It validates that all endpoints
conform to their schema definitions.
"""

import pytest
import schemathesis
from unittest.mock import AsyncMock, patch
import numpy as np

from examples.web_server.app import create_app

# Create schema from ASGI app
app = create_app()
schema = schemathesis.openapi.from_asgi("/openapi.json", app=app)


@pytest.fixture(autouse=True)
def mock_tts_provider():
    """Mock TTS provider for all schema tests."""
    with patch("examples.web_server.routes.tts.TTSRegistry") as mock_registry:
        mock_provider = AsyncMock()
        mock_audio = np.array([0, 100, -100, 0], dtype=np.int16)
        mock_provider.synthesize.return_value = mock_audio
        mock_registry.create.return_value = mock_provider
        yield mock_registry


# Test all REST endpoints against their OpenAPI schema
# Note: WebSocket endpoints (/ws/*) are excluded as Schemathesis doesn't support them
@schema.parametrize()
def test_api_schema_conformance(case):
    """Test that API endpoints conform to their OpenAPI schema.

    This test automatically:
    - Validates request schema compliance
    - Validates response status codes (allows undocumented codes from middleware)
    - Validates response schema compliance
    - Tests various input combinations generated by Hypothesis

    Schemathesis will generate test cases for all REST endpoints:
    - GET /api/health
    - GET /api/config
    - POST /api/tts

    Note: We exclude the status_code_conformance check because FastAPI middleware
    can return additional status codes (e.g., 400 for malformed JSON parsing)
    that aren't documented in the endpoint's OpenAPI schema.
    """
    # Skip WebSocket endpoints (not supported by Schemathesis ASGI testing)
    if case.path.startswith("/ws/"):
        pytest.skip("WebSocket endpoints not supported in ASGI schema tests")

    # Exclude status code conformance check - FastAPI middleware returns codes
    # that aren't in the endpoint schema (e.g., 400 for malformed JSON)
    case.call_and_validate(checks=(
        schemathesis.checks.not_a_server_error,
        schemathesis.checks.response_schema_conformance,
        schemathesis.checks.content_type_conformance,
        schemathesis.checks.response_headers_conformance,
    ))
